// <auto-generated />
using FlagApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlagApp.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20211115141304_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlagApp.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorName = "Kırmızı"
                        },
                        new
                        {
                            Id = 2,
                            ColorName = "Beyaz"
                        },
                        new
                        {
                            Id = 3,
                            ColorName = "Mavi"
                        });
                });

            modelBuilder.Entity("FlagApp.Models.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Flags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Türkiye"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Arjantin"
                        });
                });

            modelBuilder.Entity("FlagColor", b =>
                {
                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("FlagId")
                        .HasColumnType("int");

                    b.HasKey("ColorId", "FlagId");

                    b.HasIndex("FlagId");

                    b.ToTable("FlagColor");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            FlagId = 1
                        },
                        new
                        {
                            ColorId = 2,
                            FlagId = 1
                        },
                        new
                        {
                            ColorId = 2,
                            FlagId = 2
                        },
                        new
                        {
                            ColorId = 3,
                            FlagId = 2
                        });
                });

            modelBuilder.Entity("FlagColor", b =>
                {
                    b.HasOne("FlagApp.Models.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlagApp.Models.Flag", null)
                        .WithMany()
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
